### ISSUE TITLE
Hi, I can't build into WebAssembly

### ISSUE THREAD

**Issue by Mrcooder** [lukka/CppOpenGLWebAssemblyCMake#5]
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
make[2]: *** [subrepos/glfw/src/CMakeFiles/glfw.dir/cocoa_joystick.m.o] Error 1
make[2]: *** [subrepos/glfw/src/CMakeFiles/glfw.dir/monitor.c.o] Error 1
1 error generated.
shared:ERROR: '/Users/liyunhang/Documents/code/emsdk/fastcomp/fastcomp/bin/clang -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=38 -D__EMSCRIPTEN_tiny__=42 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/include/libcxx -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/lib/libcxxabi/include -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/include/compat -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/include -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/include/libc -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/local/include -DEMSCRIPTEN -D_GLFW_USE_CONFIG_H -I/Users/liyunhang/Documents/code/CppOpenGLWebAssemblyCMake -I/Users/liyunhang/Documents/code/CppOpenGLWebAssemblyCMake/subrepos/glfw/include -I/Users/liyunhang/Documents/code/CppOpenGLWebAssemblyCMake/subrepos/glfw/src -I/Users/liyunhang/Documents/code/CppOpenGLWebAssemblyCMake/build/subrepos/glfw/src -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC -Wall -c /Users/liyunhang/Documents/code/CppOpenGLWebAssemblyCMake/subrepos/glfw/src/init.c -Xclang -disable-O0-optnone -Xclang -isystem/Users/liyunhang/Documents/code/emsdk/fastcomp/emscripten/system/include/SDL -c -o CMakeFiles/glfw.dir/init.c.o -emit-llvm' failed (1)
make[2]: *** [subrepos/glfw/src/CMakeFiles/glfw.dir/init.c.o] Error 1
make[1]: *** [subrepos/glfw/src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2

------
Thank you for you did. Above was one of i got errors. Could you help me?

**Comment by lukka** [comment]
@Mrcooder can you provide the full log of the build? Seems like the Carbon.h file is missing or the header path is no properly set in compiler flags.

**Comment by lukka** [comment]
@Mrcooder I fixed some typos and on the pull request the builds run successfully either on CI (emscripten version `tag-1.38.43`) and locally with emscripten `sdk-1.38.31-64bit`. 

I would suggest you to try with the one of two versions of emscripten above, or to try on an another machine which can help sorting out what the problem is, let me know!

**Comment by Mrcooder** [comment]
> @Mrcooder I fixed some typos and on the pull request the builds run successfully either on CI (emscripten version `tag-1.38.43`) and locally with emscripten `sdk-1.38.31-64bit`.
> 
> I would suggest you to try with the one of two versions of emscripten above, or to try on an another machine which can help sorting out what the problem is, let me know!

Thank you for your did

**Comment by lukka** [comment]
@Mrcooder let me know if you managed to get the game built!
