### ISSUE TITLE
Assertion failed: f != 0 && "could not open rom file!", at: /usr/local/src/CppOpenGLWebAssemblyCMake/galaga/GalagaRoms.cpp,17,LoadFile

### ISSUE THREAD

**Issue by popomen** [lukka/CppOpenGLWebAssemblyCMake#8]
![image](https://user-images.githubusercontent.com/59364722/82006913-77aac900-969b-11ea-91f7-46410cc24f2b.png)

**Comment by lukka** [comment]
@popomen  this is a duplicate of this one:
https://github.com/lukka/CppOpenGLWebAssemblyCMake/issues/2
